FROM ubuntu:latest
LABEL org.opencontainers.image.authors="cuijinjincui4@gmail.com>"

RUN apt-get update -y
RUN apt-get install -y python3.6 python3-pip

RUN mkdir /app
WORKDIR /app
ADD requirements.txt /app/

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
ADD . /app/

ENTRYPOINT ["python3"]
CMD ["vcf2circos/dashapp.py"]